OtomasyonHotelMVC/Areas/Admin/Controllers/HotelsController.cs
using BusinessLayer.Managers;
using Entity.Models;
using Entity.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OtomasyonHotelMVC.Areas.Admin.Controllers
{
    public class HotelsController : Controller
    {
        #region Eklenecekler
        //ActivityManager activityManager = new ActivityManager();
        //ActivityHistory
        //    Campaign
        //     CampaignQuantityTypeManager;
        //    CampaignQuantityTypeHistoryManager;
        //    CampaignStatusManager;
        //    CampaignUsingManager;
        //    CampaignUsingHistoryManager;
        //    CampaignCategoryManager;
        //    CampaignCategoryHistoryManager;
        //    CampaignCode;
        //    CampaignCodeHistory ;
        //    CampaignHistory;
        //    Client ;
        //    ClientUserHistory;
        //    Complaint ;
        //    ComplaintHistory ;
        //    Floors ;
        //    FloorsHistory ;
        //    Food ;
        //    FoodCategory;
        //    FoodCategoryHistory;
        //    FoodDetail ;
        //    FoodHistory );
        //    FoodMenu ;
        //    FoodMenuHistory ;
        //    FoodTime ;
        //    FoodTimeHistory ;
        //    HotelGallery ;
        //    HotelGalleryHistory ;
        //    Order ;
        //    OrderHistory ;
        //    Personel ;
        //    PersonelUserHistory;
        //    Position ;
        //    PositionHistory ;

        //    ProductCategory ;
        //    ProductCategoryHistory ;
        //    ProductDetail ;
        //    ProductHistory ;
        //    ProductQuantityType;
        //    ProductQuantityTypeHistory ;
        //    Rol ;
        //    RolHistory ;
        //    Room  ;
        //    RoomHistory ;
        //    SatisfactionStatus ;
        //    ServiceAssignment ;
        //    ServiceAssignmentHistory ;
        //    ServiceType;
        //    ServiceTypeHistory ;
        //    ShoppingCart ;
        //    ShoppingCartHistory ;
        //    Supplier ;
        //    UserRol;
        //    SupplierHistory ;

        #endregion



        HotelsManager hotelsManager = new HotelsManager();
        RegionManager regionManager=new RegionManager() ;
        DistrictManager districtManager = new DistrictManager();
        CityManager cityManager=new CityManager();
        //ProductManager productManager = new ProductManager();

        
        // GET: Admin/Hotels
        public ActionResult Index()
        {
            var liste = hotelsManager.ListAll();
            return View(liste);
            
        }
        private void Listes()
        {
            List<SelectListItem> regionlst = (from i in regionManager.ListAll()
                                              select new SelectListItem
                                              {
                                                  Text = i.RegionName,
                                                  Value = i.Id.ToString()
                                              }
                                ).ToList();
            ViewBag.Region = regionlst;

            List<SelectListItem> citylst = (from i in cityManager.ListAll()
                                            select new SelectListItem
                                            {
                                                Text = i.CityName,
                                                Value = i.Id.ToString()
                                            }
                                            ).ToList();
            ViewBag.City = citylst;

            List<SelectListItem> districtlst = (from i in districtManager.ListAll()
                                                select new SelectListItem
                                                {
                                                    Text = i.DistrictName,
                                                    Value = i.Id.ToString()
                                                }
                                            ).ToList();
            ViewBag.District = districtlst;
        }
        public ActionResult RegisterHotel()
        {
            Listes();
            HotelsViewModel hvm = new HotelsViewModel();
           
            return View(hvm);
        }
        [HttpPost]
        public ActionResult RegisterHotel(HotelsViewModel hotels)
        {
            if (hotels.Id == 0)
            {
                if (Request.Files.Count > 0)
                {
                    if (Request.Files[0].FileName == "")
                    {
                        hotels.HotelPhoto = "HotelNull.png";
                    }
                    else if (Request.Files[0].FileName != "")
                    {
                        string Dosyaadi = Guid.NewGuid().ToString();
                        string Uzanti = Path.GetExtension(Request.Files[0].FileName);
                        string Yol = "~/img/Hotels/" + Dosyaadi + Uzanti;
                        Request.Files[0].SaveAs(Server.MapPath(Yol));
                        hotels.HotelPhoto =  Dosyaadi + Uzanti;
                    }

                }

                hotelsManager.HotelsRegister(hotels);
            }
            else
            {
                var kontrol = hotelsManager.ListAll(x=>x.Id==hotels.Id).FirstOrDefault();
                if (kontrol != null)
                {
                    if (Request.Files.Count > 0)
                    {
                        if (kontrol.HotelPhoto == "" || kontrol.HotelPhoto == null && Request.Files[0].FileName == "")
                        {
                            hotels.HotelPhoto = "~/img/Hotel/HotelNull.png";

                        }
                        else if (Request.Files[0].FileName != "")
                        {
                            string Dosyaadi = Guid.NewGuid().ToString();
                            string Uzanti = Path.GetExtension(Request.Files[0].FileName);
                            string Yol = "~/img/Hotel/" + Dosyaadi + Uzanti;
                            Request.Files[0].SaveAs(Server.MapPath(Yol));
                            hotels.HotelPhoto = Dosyaadi + Uzanti;
                        }
                    }
                    
                    hotelsManager.HotelsUpdate(hotels);
                  

                    }
                }

     






            Listes();
            return View();
        }

        //public ActionResult HotelDelete(int id)
        //{//Test Edilecek.
           
        //    var kontrol = productManager.ProductGetAll(x => x.Hotelid == id).FirstOrDefault();
        //    if (kontrol == false)
        //    {
             
        //        var kontrol2 = productManager.GetAll(x=>x.Hotelid==id) ;
        //        if (kontrol2 == true)
        //        {
              
        //        }
        //        else
        //        {
        //            ViewBag.Hata2 = "Ürünler Tablosunda İlişkili Veriler Var ";
        //        }
        //    }
        //    else
        //    {
        //        ViewBag.Hata1 = "Personel Tablosunda İlişkili Veriler Var ";
        //    }
        //    return View();
        //}
    }
}

OtomasyonHotelMVC/Areas/Admin/Views/Hotels/Index.cshtml
@using Entity.ViewModels
@model List<HotelsViewModel>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
         Fotoğraf
        </th>
        <th>
          Hotel Adı
        </th>
        <th>
          Adres
        </th>
        <th>
         Kuruluş Yılı
        </th>
        <th>
            Aktif Mi?
        </th>
     
   

    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.hotelPhoto)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.hotelName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.hotelAddress)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.foundationYear)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.isAktive)
    </td>

    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "HotelDelete", new { id = item.Id })
    </td>
</tr>
}

</table>

OtomasyonHotelMVC/Areas/Admin/Views/Hotels/RegisterHotel.cshtml
@model Entity.ViewModels.HotelsViewModel
<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

@using (Html.BeginForm("RegisterHotel", "Hotels", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" style="text-align:center">
    <h4 class=" card-footer">    <b>Hotel Bilgileri</b></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class=" row">
        <div class="col-md-6 col-lg-3 col-sm-12">
            <div class="form-group card-body">
                @if (Model.hotelPhoto == null || Model.hotelPhoto == "")
                {
                    <img src="~/img/Hotels/HotelNull.png" width="200" height="200" class="card card-body imghotel">

                }
                else if (Model.hotelPhoto != null || Model.hotelPhoto != null)
                {
                    <img src="~/img/Hotels/@Html.DisplayFor(x => x.hotelPhoto)" width="200" height="200" class="card card-body imghotel">

                }

            </div>
            <div class="form-group" style="margin-top:1%">
                <br />    @*Photo Başlama*@
                <div id="fotoekle" class="col-md-3 test">

                    <input type="file" name="hotelPhoto" />
                    <br />
                </div>
                @*photo bitme*@
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.hotelName, htmlAttributes: new { @class = "control-label  col-md-12" })
                <div class="col-md-12 col-sm-12 col-lg-12">
                    @Html.EditorFor(model => model.hotelName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.hotelName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.hotelAddress, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12 col-sm-12 col-lg-12">
                    @Html.TextAreaFor(model => model.hotelAddress, 5, 20, new { @class = "text-area" })
                    @Html.ValidationMessageFor(model => model.hotelAddress, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-6 col-lg-3 col-sm-12">

            <div class="form-group">
                @Html.LabelFor(model => model.regionName, htmlAttributes: new { @class = "control-label col-md-12 " })
                <div class="col-md-12 col-sm-12 col-lg-11">
                    @Html.DropDownListFor(m => m.regionId, (List<SelectListItem>)ViewBag.Region, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.cityName, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12 col-sm-12 col-lg-11">
                    @Html.DropDownListFor(m => m.cityId, (List<SelectListItem>)ViewBag.City, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.districtName, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12 col-sm-12 col-lg-11">
                    @Html.DropDownListFor(m => m.districtId, (List<SelectListItem>)ViewBag.District, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group row col-md-12 col-sm-12 col-lg-12">
                <div class="col-md-12 col-sm-6 col-lg-6" style="float:left">
                    Kat Sayısı
                    @Html.TextBoxFor(m => m.districtId, new { @class = "form-control" })
                </div>
                <div class=" col-md-12 col-sm-6 col-lg-6 " style="float:right">
                    Oda Sayısı

                    @Html.TextBoxFor(m => m.districtId, new { @class = "form-control" })
                </div>

            </div>
        </div>
        <div class="col-md-6 col-lg-3 col-sm-12 ">
            <div class="form-group  ">
                Kuruluş Yılı
                <div class="col-md-12 col-sm-12 col-lg-11 ">
                    @Html.TextBoxFor(m => m.foundationYear, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                Faaliyet Durumu
                <div class="col-md-12 col-sm-12 col-lg-11">
                    @Html.CheckBoxFor(m => m.isAktive) Aktif
                </div>
            </div>   <div class="form-group">
                @*BURASİ HOTEL EKLERKEN GÖZÜKMEYECEK DÜZELTİRKEN POPUP OLARAK DÜZELTME YAPACAK*@
                <div class="col-md-12 col-sm-12 col-lg-11">
                    <input type="button" value=" Kat Şeması Oluştur" class="form-control" />
                </div>
            </div>
        </div>


    </div>
    @Html.HiddenFor(x => x.Id)
    <div class="float-left">
        * Kat Şeması oluşturmak için Önce Hotel Bilgilerini Ekleyiniz Sonra Hotels Menüsünden Hoteli Seçip Düzeltme İşlemi Yapabilirsiniz.
    </div><br />
    @if (ViewBag.Resul != null)
    {
        <div class=" alert alert-@ViewBag.Status" role="alert">@ViewBag.Result</div>
    }

    <div class="form-group " style="text-align:right">
        <hr /><br />
        <div class="col-md-offset-2 col-sm-offset-1 col-md-6 col-sm-12">
            <input type="submit" value="Kaydet" class="btn btn-success" />
            <input type="reset" value="İptal" class="btn btn-danger" />
        </div>
    </div>
</div>
}